spring:
  #MySQL连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/straw?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    #数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      max-active: 10
      min-idle: 2
  #应用程序名称
  application:
    name: api-user
#mybatis的Mapper文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #设置项目运行的端口号
server:
  port: 8080
eureka:
  instance:
    #是否使用ip来注册，反则用主机名注册
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}@${eureka.instance.ip-address}:${server.port}
